# Generated by Django 5.2.1 on 2025-05-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nid", "0002_niduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="niduser",
            name="user",
        ),
        migrations.AlterField(
            model_name="niduser",
            name="nid",
            field=models.BigIntegerField(),
        ),
    ]
