# Generated by Django 5.2.1 on 2025-05-12 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nid", "0002_alter_nid_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nid",
            unique_together={("user", "nid")},
        ),
    ]
